version: '3.4'

services:
  service:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    image: "udafullstack/service"
    env_file:
      - ${PWD}/service/simple-jwt-api.env
    ports:
      - "58080:8080"
    volumes:
      # remove the following for production with Dockerfile ADD
      - ${PWD}/service/application:/app/application
      - ${PWD}/service/tests:/app/tests
      - ${PWD}/service/config.py:/app/config.py
      - ${PWD}/service/main.py:/app/main.py
      - ${PWD}/service/requirements.txt:/app/requirements.txt
      - ${PWD}/service/uwsgi.ini:/app/uwsgi.ini      