apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::112924623848:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-CXBRB58CU6J1
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-03-04T07:16:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "802"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 236dc5e4-5de8-11ea-b9b7-0a69543f324e
